[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "prague"  # Enable EIP-7702 support
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = false

# Flow EVM Configuration
[rpc_endpoints]
flow_testnet = "https://testnet.evm.nodes.onflow.org"
flow_mainnet = "https://mainnet.evm.nodes.onflow.org"
local = "http://127.0.0.1:8545"

[etherscan]
flow_testnet = { key = "${FLOW_ETHERSCAN_API_KEY}", url = "https://evm-testnet.flowscan.io/api" }
flow_mainnet = { key = "${FLOW_ETHERSCAN_API_KEY}", url = "https://evm.flowscan.io/api" }

# EIP-7702 specific profile for testing
[profile.eip7702]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "prague"
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 1000

# Flow local testing profile  
[profile.flow-local]
src = "src"
out = "out" 
libs = ["lib"]
evm_version = "prague"
solc_version = "0.8.26"
optimizer = false
